spring:
  application:
    name: taurai-rtc
  datasource:
    url: jdbc:postgresql://localhost:5432/taurai
    username: ianjunior
    password: IJNaomi@2003
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect