spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/{PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
  
  jpa:
    hibernate:
      ddl-auto: update  # Create tables automatically in prod
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: false

# Production logging
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.tool.hbm2ddl: DEBUG
    org.springframework.jdbc.datasource: DEBUG
    com.zaxxer.hikari: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"