spring:
  datasource:
    url: ${JDBC_DATABASE_URL:${DATABASE_URL}}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
  
  jpa:
    hibernate:
      ddl-auto: update  # Create tables automatically in prod
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: false

# Production logging
logging:
  level:
    com.hexicode: DEBUG
    org.springframework: INFO
    org.springframework.boot: INFO
    org.springframework.web.socket: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.zaxxer.hikari: DEBUG
    org.postgresql: DEBUG
    jdbc.sqltiming: DEBUG
    org.springframework.boot.autoconfigure: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"